services:
  backend:
    build: ./news-portal
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./news-portal:/dj_news_app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  frontend:
    build: ./client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=misha
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dj_news_app
volumes:
  postgres_data: