# Generated by Django 4.0.2 on 2022-04-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_post_user_id_alter_user_company_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
