# Generated by Django 4.0.2 on 2022-05-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
